/**
 * Enterprise Resource Assignment Types
 */
export enum AssignmentType {
  PRIMARY_OWNER = 'PRIMARY_OWNER',
  PLANNER = 'PLANNER',
  DISPATCHER = 'DISPATCHER',
  DRIVER = 'DRIVER',
  CARRIER = 'CARRIER',
  CUSTOMER = 'CUSTOMER',
  FINANCE_OWNER = 'FINANCE_OWNER',
  COMPLIANCE_OWNER = 'COMPLIANCE_OWNER',
  SUPPORT_OWNER = 'SUPPORT_OWNER',
  APPROVER = 'APPROVER',
  REVIEWER = 'REVIEWER',
}
