const ACTION_LABELS: Record<string, string> = {
  'action-save': 'Save / Accept (Ctrl+A)',
  'action-form-save': 'Form Quick Save (Ctrl+S)',
  'action-new': 'New Voucher / Create (Alt+C)',
  'action-edit': 'Edit / Alter Record (Ctrl+Enter)',
  'action-delete': 'Delete Selected (Delete)',
  'action-refresh': 'Refresh Active View (Alt+R)',
  'action-search': 'Quick Filter / Search (Alt+F)',
  'action-export': 'Export Data to Excel (Alt+E)',
  'action-print': 'Print Document / PDF (Alt+P)',
  'action-help': 'Help & Keyboard Cheat-Sheet (F1)',
  'action-cancel': 'Cancel / Exit Layer (Ctrl+Q / Esc)',
  'switch-company': 'Select / Switch Company (Alt+F3)',
  'desk-keys': 'Keyboard Shortcuts Configuration (Ctrl+Alt+K)',
  'grid-cell-dialog': 'Open Cell Detail Dialog (Ctrl+Enter)',
  'desk-jump': 'Jump to Next Form Zone (Ctrl+Enter)',
  'desk-move-up': 'Move to Field Above (Ctrl+Up)',
  'desk-move-down': 'Move to Field Below (Ctrl+Down)',
  'desk-move-left': 'Move to Field Left (Ctrl+Left)',
  'desk-move-right': 'Move to Field Right (Ctrl+Right)',
  'desk-tab-prev': 'Previous Tab Page (Ctrl+Shift+Left)',
  'desk-tab-next': 'Next Tab Page (Ctrl+Shift+Right)',

  // Navigation targets
  'nav-dashboard': 'Go to Operations Dashboard',
  'nav-lrs': 'Go to Lorry Receipts (LRs / Consignment Notes)',
  'nav-trips': 'Go to Trips / Load Plans',
  'nav-fuel': 'Go to Fuel Log & Mileage Entries',
  'nav-advances': 'Go to Driver Advances & Cash',
  'nav-pods': 'Go to Proof of Delivery (POD) Processing',
  'nav-invoices': 'Go to Customer Freight Invoices',
  'nav-purchase-bills': 'Go to Carrier / Vendor Purchase Bills',
  'nav-settlements': 'Go to Driver & Trip Settlements',
  'nav-vehicles': 'Go to Fleet & Vehicles Master',
  'nav-drivers': 'Go to Drivers & Operators Master',
  'nav-customers': 'Go to Customers / Debtors Master',
  'nav-carriers': 'Go to Transporters & Carriers Master',
  'nav-routes': 'Go to Routes & Toll Master',
  'nav-branches': 'Go to Branches & Hubs',
  'nav-tyres': 'Go to Tyre Management & Inventory',
  'nav-maintenance': 'Go to Vehicle Maintenance & Job Cards',
  'nav-reports': 'Go to Reports & Analytics',
  'nav-exceptions': 'Go to Operational Exceptions',
  'nav-copilot': 'Go to Dispatch AI & Suggestions',
  'nav-users': 'Go to Users & Team Management',
  'nav-roles': 'Go to Roles & Permissions',
  'nav-company-settings': 'Go to Company Settings',
  'nav-period-lock': 'Go to Period Locks & Fiscal Lock',
};

export function tmsActionLabel(actionId: string): string {
  return ACTION_LABELS[actionId] ?? actionId.replace(/-/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
}
