import { OrganizationModel } from './auth/organization.model';
import { UserModel } from './auth/user.model';
import { RoleModel } from './auth/role.model';
import { PermissionModel } from './auth/permission.model';
import { RolePermissionModel } from './auth/role-permission.model';
import { UserRoleModel } from './auth/user-role.model';

import {
  LocationTypeModel,
  LocationModel,
  VehicleTypeModel,
  CargoTypeModel,
  PackageTypeModel,
} from './master-data/master-data.model';
import { FacilityModel, DockModel, AppointmentModel } from './master-data/facility.model';

import {
  CustomerModel,
  CarrierModel,
  CarrierContractModel,
  CarrierRateModel,
  CarrierDocumentModel,
} from './partners/partners.model';

import {
  VehicleModel,
  VehicleDocumentModel,
  VehicleMaintenanceModel,
  DriverModel,
  DriverDocumentModel,
  DriverAssignmentModel,
  FuelEntryModel,
} from './fleet/fleet.model';

import {
  TransportOrderModel,
  OrderItemModel,
  ShipmentModel,
  ShipmentItemModel,
  RouteModel,
  RouteStopModel,
  LoadPlanModel,
  LoadPlanItemModel,
  DispatchModel,
  TenderRequestModel,
  DriverAdvanceModel,
  TyreEventModel,
  TyreInventoryModel,
  JobCardModel,
  PodRecordModel,
  BillingInvoiceModel,
  PurchaseBillModel,
  SettlementModel,
} from './operations/operations.model';

import {
  TrackingEventModel,
  GeofenceModel,
  GeofenceEventModel,
  ProofOfDeliveryModel,
  LorryReceiptModel,
} from './telematics/telematics.model';

import {
  InvoiceModel,
  InvoiceItemModel,
  PaymentModel,
  TripExpenseModel,
  ClaimModel,
  ClaimItemModel,
  AccountingSyncModel,
} from './finance/finance.model';

import {
  NotificationModel,
  AuditLogModel,
  AnalyticsDataModel,
  DocumentTypeModel,
  DocumentModel,
  DemoRequestModel,
} from './system/system.model';

export {
  OrganizationModel,
  UserModel,
  RoleModel,
  PermissionModel,
  RolePermissionModel,
  UserRoleModel,
  LocationTypeModel,
  LocationModel,
  VehicleTypeModel,
  CargoTypeModel,
  PackageTypeModel,
  FacilityModel,
  DockModel,
  AppointmentModel,
  CustomerModel,
  CarrierModel,
  CarrierContractModel,
  CarrierRateModel,
  CarrierDocumentModel,
  VehicleModel,
  VehicleDocumentModel,
  VehicleMaintenanceModel,
  DriverModel,
  DriverDocumentModel,
  DriverAssignmentModel,
  FuelEntryModel,
  TransportOrderModel,
  OrderItemModel,
  ShipmentModel,
  ShipmentItemModel,
  RouteModel,
  RouteStopModel,
  LoadPlanModel,
  LoadPlanItemModel,
  DispatchModel,
  TenderRequestModel,
  DriverAdvanceModel,
  TyreEventModel,
  TyreInventoryModel,
  JobCardModel,
  PodRecordModel,
  BillingInvoiceModel,
  PurchaseBillModel,
  SettlementModel,
  TrackingEventModel,
  GeofenceModel,
  GeofenceEventModel,
  ProofOfDeliveryModel,
  LorryReceiptModel,
  InvoiceModel,
  InvoiceItemModel,
  PaymentModel,
  TripExpenseModel,
  ClaimModel,
  ClaimItemModel,
  AccountingSyncModel,
  NotificationModel,
  AuditLogModel,
  AnalyticsDataModel,
  DocumentTypeModel,
  DocumentModel,
  DemoRequestModel,
};

export const ALL_MODELS = [
  OrganizationModel,
  UserModel,
  RoleModel,
  PermissionModel,
  RolePermissionModel,
  UserRoleModel,
  LocationTypeModel,
  LocationModel,
  VehicleTypeModel,
  CargoTypeModel,
  PackageTypeModel,
  FacilityModel,
  DockModel,
  AppointmentModel,
  CustomerModel,
  CarrierModel,
  CarrierContractModel,
  CarrierRateModel,
  CarrierDocumentModel,
  VehicleModel,
  VehicleDocumentModel,
  VehicleMaintenanceModel,
  DriverModel,
  DriverDocumentModel,
  DriverAssignmentModel,
  FuelEntryModel,
  TransportOrderModel,
  OrderItemModel,
  ShipmentModel,
  ShipmentItemModel,
  RouteModel,
  RouteStopModel,
  LoadPlanModel,
  LoadPlanItemModel,
  DispatchModel,
  TenderRequestModel,
  DriverAdvanceModel,
  TyreEventModel,
  TyreInventoryModel,
  JobCardModel,
  PodRecordModel,
  BillingInvoiceModel,
  PurchaseBillModel,
  SettlementModel,
  TrackingEventModel,
  GeofenceModel,
  GeofenceEventModel,
  ProofOfDeliveryModel,
  LorryReceiptModel,
  InvoiceModel,
  InvoiceItemModel,
  PaymentModel,
  TripExpenseModel,
  ClaimModel,
  ClaimItemModel,
  AccountingSyncModel,
  NotificationModel,
  AuditLogModel,
  AnalyticsDataModel,
  DocumentTypeModel,
  DocumentModel,
  DemoRequestModel,
];
