/**
 * Writes docs/entity-flow.md: for every CRUD entity, the files that make it up, its write path
 * (hooks and service overrides), dependents and actions with their permissions. Generated from
 * the running app, so it cannot drift from the code.   Run: npm run flow
 */
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { NestFactory, ModulesContainer } from '@nestjs/core';
import { AppModule } from '../app.module.js';
import { TenantCrudService, type EntityFlow } from '../framework/crud/tenant-crud.service.js';

const MODULES = join(process.cwd(), 'src', 'modules');

function listFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? listFiles(path) : [path];
  });
}

/** The module folder whose service declares `resource = '<resource>'`. */
function folderOf(resource: string): string | null {
  for (const folder of readdirSync(MODULES)) {
    const dir = join(MODULES, folder);
    if (!statSync(dir).isDirectory()) continue;
    const owns = listFiles(dir).some((file) => file.endsWith('.service.ts') && readFileSync(file, 'utf8').includes(`resource = '${resource}'`));
    if (owns) return dir;
  }
  return null;
}

const ROUTES: Record<string, (op: EntityFlow['operations'][number]) => string> = {
  row: (op) => `\`POST /:id/actions/${op.name}\``,
  bulk: (op) => `\`POST /actions/${op.name}\` with \`{ ids }\` - one transaction, steps run per record, blockers reported per record`,
  collection: (op) => `\`POST /actions/${op.name}\` - no record`,
  list: (op) => (op.name === 'list' ? 'every list' : `\`GET /?view=${op.name.slice(5)}\` - after the shared \`list/\` steps`),
  view: (op) => `\`GET /:id/views/${op.name.slice(5)}\` - read only`,
};

function render(flow: EntityFlow): string {
  const dir = folderOf(flow.resource);
  const files = dir ? listFiles(dir).map((file) => relative(dir, file)).sort() : [];
  const lines = [
    `## ${flow.label} (\`${flow.resource}\`)`,
    '',
    `Folder: \`${dir ? relative(process.cwd(), dir) : '?'}\``,
    '',
    '```',
    ...files,
    '```',
  ];
  if (flow.dependents.length) lines.push('', `Delete is blocked while used by: ${flow.dependents.map((d) => `\`${d}\``).join(', ')}`);

  for (const op of flow.operations) {
    const route = ROUTES[op.kind]?.(op) ?? '';
    const from = op.from ? ` · from ${Object.entries(op.from).map(([field, values]) => `${field}: ${values.join('/')}`).join('; ')}` : '';
    const inputs = op.inputs.length ? ` · asks ${op.inputs.join(', ')}` : '';
    lines.push('', `### ${op.name} · \`${op.permission}\`${from}${inputs}`, '', route ? `${route}` : '', '```');
    const phase = (name: string) =>
      op.steps
        .filter((step) => step.phase === name)
        .map((step) => `${step.file}${step.conditional ? '   (when' + (step.describe ? ': ' + step.describe : '') + ')' : step.describe ? '   (' + step.describe + ')' : ''}`);
    const reads = op.kind === 'list' || op.kind === 'view';
    if (op.name === 'delete' && flow.dependents.length) lines.push('   (built in) not used by: ' + flow.dependents.join(', '));
    lines.push(...phase('check'), ...(reads ? [] : ['   -- all blockers reported together; warnings wait for confirm --']), ...phase('before'));
    lines.push(`   => ${op.effect}`, ...phase('after'), '```');
  }
  return lines.join('\n');
}

async function run() {
  const app = await NestFactory.createApplicationContext(AppModule, { logger: ['error'] });
  const flows: EntityFlow[] = [];
  for (const module of app.get(ModulesContainer).values()) {
    for (const wrapper of module.providers.values()) {
      if (wrapper.instance instanceof TenantCrudService && wrapper.instance.resource) flows.push(wrapper.instance.describeFlow());
    }
  }
  flows.sort((a, b) => a.label.localeCompare(b.label));

  const header = `# Entity flow

Generated by \`npm run flow\`. Do not edit.

Every entity is one folder under \`src/modules\`. Its service is configuration only; what each
operation does is the step files of \`ops/<operation>/\`, run in file-name order in one transaction:

\`\`\`
ops/save/       steps for both create and update      ops/delete/
ops/create/     create only                            ops/<action>/  one folder per named action
ops/update/     update only

NNN-check-name.ts    001-399  read only; add issues; leave facts in state
NNN-before-name.ts   400-499  after checks passed and the user confirmed
                              => the main change (insert, update, delete, or the action's run)
500-execute.ts       500      optional: replaces the main change (original() runs the built-in one)
NNN-after-name.ts    501-999  children, related records, other entities

list/, list-<view>/  before = shape the query (push to c.where/include/order), after = decorate c.rows
view-<name>/         read one record; steps build c.result
<action>/            kind row | bulk (ids, per-record blockers) | collection (no record)
\`\`\`

Files not starting with a number (\`_state.ts\`, \`_shared/\`) are helpers. Each operation ends with an audit row.
Every create, edit, delete and action is also listed per row at \`GET /<resource>/:id/history\`.
`;
  mkdirSync('docs', { recursive: true });
  writeFileSync('docs/entity-flow.md', `${header}\n${flows.map(render).join('\n\n')}\n`);
  console.log(`docs/entity-flow.md: ${flows.length} entities`);
  await app.close();
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});

